# Generated by Django 5.2.3 on 2025-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.CharField(choices=[('foto1.png', 'Foto 1'), ('foto2.png', 'Foto 2'), ('foto3.png', 'Foto 3'), ('foto4.png', 'Foto 4'), ('foto5.png', 'Foto 5'), ('foto6.png', 'Foto 6')], default='foto1.png', max_length=50),
        ),
    ]
