# Generated by Django 4.2.5 on 2025-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0013_compostagem_fkusuario_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='compostagem',
            name='data_pronto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
