# Generated by Django 5.2.4 on 2025-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0014_compostagem_data_pronto'),
    ]

    operations = [
        migrations.AddField(
            model_name='composteira',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='composteiras/', verbose_name='Imagem da composteira'),
        ),
    ]
