# Generated by Django 4.2.5 on 2025-10-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0015_composteira_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composteira',
            name='tamanho',
        ),
    ]
